<svelte:head>
	<title>About Shamley Incorporated</title>
</svelte:head>

<h1>About Shamley Incorporated</h1>

<p>We can help level up your existing developers or assist in honing your hiring practices.</p>

<p>Holy man open up your eyes To the ways of the world you've been so blind. Slow death immense decay. An unforeseen future nestled somewhere in time. Mandatory suicide massacre on the front line. I won't be force fed prophecies From a book of untruths for the weakest mind. Bones shining by the night in blood laced misery. Fly swatter stakes drive through your chest. Corpses rotting through the night in blood laced misery. Man made virus infecting the world Self-destruct human time bomb. The way that I want you to die. Spikes impale you as you're forced off the crest. Spikes impale you as you're forced off the crest. The pendulum it shaves the blade the strafing air blood raid. Feel the knife pierce you intensely.</p>

<p>The way that I want you to die. Man made virus infecting the world Self-destruct human time bomb. Hunting with bated breath. Not once has anyone ever seen Such a rise of pure hypocrisy. Corpses rotting through the night in blood laced misery. Propaganda death ensemble burial to be. Sadistic surgeon of demise sadist of the noblest blood. Cut throat slit your wrist shoot you in the back fair game. Betrayed by many now ornaments dripping above. Radical amputation this is insane. Spikes impale you as you're forced off the crest. I'll never be the one to blindly follow. Tell me what you think of your savior now. Indication of triumph: the numbers that are dead.</p>

<p>Tell me what you think of your savior now. Bombard till submission take all to their graves. I won't be force fed prophecies From a book of untruths for the weakest mind. Infiltration push reserves encircle the front lines. The pendulum it shaves the blade the strafing air blood raid. Tell me what it's like when the celebration begins. Unsuspecting victims no warnings no signs. The final swing is not a drill. Lying dying screaming in pain. Slow death immense decay. Drones since the dawn of time. Fall into me the sky's crimson tears. Dead bodies dying and wounded. Awaiting reprisal.</p>

<p>Tell me what you think of your savior now. It's how many people I can kill. Litter the city streets. Bones shining by the night in blood laced misery. As the walls of religion come crashing down. I'll instigate I'll free your mind I'll show you what I've known all this time. Drug abuse self abuse searching for the next high. An unforeseen future nestled somewhere in time. Holy man open up your eyes To the ways of the world you've been so blind. Bones shining by the night in blood laced misery. Bombard till submission take all to their graves. What if there is no God would you think the fuckin' same Wasting your life in a leap of blind faith. What if there is no God would you think the fuckin' same Wasting your life in a leap of blind faith. Dismiss it as the folklore of the times.</p>

<p>As the walls of religion come crashing down. Mines explode pain sheers through your brain. Bones shining by the night in blood laced misery. From a lacerated sky Bleeding its horror Creating my structure. Cut throat slit your wrist shoot you in the back fair game. Infiltration push reserves encircle the front lines. Holy man open up your eyes To the ways of the world you've been so blind. Dismiss it as the folklore of the times. I'm waiting for the day the whole world fucking dies. I'll instigate I'll free your mind I'll show you what I've known all this time. The sport is war total war. Cut throat slit your wrist shoot you in the back fair game. Supreme art of strategy playing on the minds. Holy man open up your eyes To the ways of the world you've been so blind.</p>